hichip_db_py: "/mnt/BioAdHoc/Groups/vd-ay/jreyna/software/mambaforge/envs/hichip-db/bin/python"
hic_tls_py: "/mnt/BioHome/jreyna/software/anaconda3/envs/hic_tls/bin/python"
hic_tls_R: "/share/apps/R/3.4.3/lib64/R/bin/Rscript"
R4: "/mnt/BioHome/jreyna/R-Versions/R-4.0.3/bin/Rscript"
fithic: "/mnt/BioHome/jreyna/software/fithic/fithic/fithic.py"
fithic_tls: "/mnt/BioHome/jreyna/software/fithic/fithic/fithic_tls.py"
hicpro2fithic: "/mnt/BioHome/jreyna/software/fithic/fithic/utils/HiCPro2FitHiC.py"
hicpro_utils: "/mnt/BioHome/jreyna/software/HiC-Pro/bin/utils/"
juicer_tools: "/mnt/BioAdHoc/Groups/vd-ay/abhijit/overflow/proj_overflow/Alternate_Chromosomal_structures/juicer_tools.1.8.9_jcuda.0.8.jar"
Rpath: "/share/apps/R/3.4.3/lib64/R/bin/R"
CLINES: ["A549", "Caki2", "HEK293", "LNCaP", "NCI-H460", "Panc1", "SKNSH"]
DIXON_HIC_OVERLAPS: ["A549", "Caki2", "LNCaP", "NCI-H460", "Panc1", "SKNSH"]
DIXON_WGS_OVERLAPS: ["A549", "Caki2", "LNCaP", "NCI-H460", "Panc1"]
hictrans: "/home/jreyna/software/HiCtrans/hictrans.v3.R"
hicnv: "/home/jreyna/software/HiCnv/hicnv_v2.R"
hicnv_scripts: "/home/jreyna/software/HiCnv/scripts/"
python2: "/mnt/BioHome/jreyna/software/anaconda3/envs/python_2.7.18/bin/python"
mustache: "/mnt/BioHome/jreyna/software/anaconda3/envs/mustache/bin/mustache"
mustache_python: "/mnt/BioHome/jreyna/software/anaconda3/envs/mustache/bin/python"
juicer_tools_1.13.02: "/home/jreyna/software/juicer_tools_1.13.02.jar"
cooler: "/mnt/BioHome/jreyna/software/anaconda3/envs/hic_tls/bin/cooler"
bgzip: "/mnt/BioHome/jreyna/software/anaconda3/envs/hic_tls/bin/bgzip"
liftover: "/home/jreyna/software/UCSC_Browser_Tools/liftOver"
hichip_db_python: "/home/jreyna/software/anaconda3/hichip-db/bin/python"
